# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d301430e7cd49ec89c1056107db7297ba0345c364fcb1d18a228f995faca70a078ef86afb91c62a4e35c20865c8ed3beb772a51083958c462f8e4d61ab9e6fd

test:
  secret_key_base: 6bb75735e7e3b206e65503c0bd73418c4db6b800645ebe5b5407575928dd3b856a2481e0fa3d4dd56cac8351ddac42d66f0ac21c3a632967917436937916014c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
